### PR TITLE
fix transition issues in safari

### LINKED ISSUE #80: Issue with transitions on Safari
I faced some weird animations on Safari 8.0.8 with MacOS. Digging into the DOM did show me that there is a max-height value for accordion-item-body which is adding up to something close to 100px on my click and then less than a second changes back to none. Any ideas?

accordion-bug

### PR DESCRIPTION
**Pull request by maxnowack**
fixes #80

### CODE REVIEW

**Comment by psimyn** [comment]
could this cause issues if the AccordionItem content changes after it's expanded?

I think `preloadImages` should take care of it. I'll do a bit of testing.

Thanks for the PR

**Comment by rgagliardo** [comment]
I'm seeing this flicker transition on mobile as well - IOS/Chrome. Has this scenario been tested?

**Comment by psimyn** [comment]
@rgagliardo thanks - I had only checked OSX Safari. I assume it is some webkit issue

**Comment by brukh** [comment]
I tried this but it didn't fix the issue for me. I took a look at the component and realized we could simplify the logic and not have to use setTimeout(s). I created a PR (#97) and tested on mobile and desktop versions of Safari and Chrome. Can you guys please also test it for me? @psimyn @rgagliardo @maxnowack

**Comment by rgagliardo** [comment]
@brukh I'd love to help test, but I'm not familiar enough with github at this time. A point in the right direction, would help. I'm wondering how to incorporate these changes, so that I can test locally.

**Comment by psimyn** [comment]
thanks @rgagliardo, here's some steps for testing:

On the PR page for #97 you can see the branch name `transitionfix`

image

on your local repo, you'll need to run `git fetch` to get the new branches, then `git checkout transitionfix` and you can start testing

**Comment by rgagliardo** [comment]
@psimyn - thanks Simon. 

I tried a few things - this seemed to be the most straight forward, added this in place of the original sanfona in my package.json

"react-sanfona": "github:daviferreira/react-sanfona#pull/97/head"

I deployed this build to our devel env., but still see the flickering. So I'm not sure if the latest code is present, or the fix doesn't resolve the issue. 

I'm willing to try other avenues to help.

**Comment by ivchenkodima** [comment]
Does anybody try to fix this issue??

**Pull request closed without merging**
