### PR TITLE
Refactoring AccordionItem to fix transitions issues

### PR DESCRIPTION
**Pull request by brukh**
+ This PR fixes transition issues in Safari (mobile & desktop) and mobile Chrome.
+ Refactored component logic but should not cause conflicts with existing API.
+ Tested successfully on Safari (mobile & desktop) and Chrome (mobile & desktop)

### CODE REVIEW

**Comment by psimyn** [comment]
Not tested but if you've confirmed working in broken browsers this looks good :+1: 

Only thing it is missing is removing the maxHeight when item is expanded. If you have an AccordionItem with dynamic content (e.g. another accordion) then the contents can be clipped

**Comment by brukh** [comment]
Good catch @psimyn! Now I recalculate the maxHeight when the children change. Thank you 👍

**Comment by ivchenkodima** [comment]
Is it working now??

**Comment by brukh** [comment]
I will get this fully tested and merged by this weekend @ivchenkodima

**Comment by ivchenkodima** [comment]
@brukh do your have some progress?

**Comment by ivchenkodima** [comment]
@brukh

**Comment by brukh** [comment]
@ivchenkodima I ran into some issues on updates but I'm working on it. I want to make sure I cover all edge cases before I merge.

**Comment by ivchenkodima** [comment]
@brukh  how much time is still needed ?

**Comment by SuttJ** [comment]
Can we merge this? Not sure why it's passing but hasn't been merged.

**Pull request merged**
