### PR TITLE
BeforeChange

### PR DESCRIPTION
**Pull request by luckyraul**

### CODE REVIEW

**Comment by daviferreira** [comment]
Sorry, I don't really understand why is this needed. Can you give me a use case?

**Comment by luckyraul** [comment]
In my case to prevent to move to next tab until some service say "you can"

**Comment by daviferreira** [comment]
Can't you use the `onExpand` callback and only display the content after confirmation?

**Comment by luckyraul** [comment]
No, It can confuse users.

**Comment by luckyraul** [comment]
It will be better to make Accordion state external

**Comment by daviferreira** [comment]
Not sure about that, I want everything to be controlled via expanded prop on the items. 

I don't think using `onExpand` would confuse your users, you can just control style/content on that item from the outside.

**Comment by luckyraul** [comment]
They will feel that they proceed to the next step, however we don't

**Comment by daviferreira** [comment]
If you do something like this, it won't feel like that, just tried on the demo:

```js
<Accordion onChange={this.handleChange}>
  {[0, 1, 2, 3, 4].map(item => {
    return (
      <AccordionItem
        key={item}
        title={`Item ${item}`}
        onExpand={
          item === 2
            ? index => {
                if (window.confirm('Are you sure?')) {
                  this.setState({ confirmed: true });
                } else {
                  this.setState({ activeItems: [] });
                }
              }
            : null
        }
        expanded={this.state.activeItems.includes(item)}
      >
        <div>
          {`Item ${item} content`}
          {item === 2 ? (
            this.state.confirmed ? (
              <p>Confirmed</p>
            ) : (
              'Loading...'
            )
          ) : null}
          {item === 3 ? (
            <p>
              <img src="https://cloud.githubusercontent.com/assets/38787/8015584/2883817e-0bda-11e5-9662-b7daf40e8c27.gif" />
            </p>
          ) : null}
        </div>
      </AccordionItem>
    );
  })}
</Accordion>;
```

**Comment by luckyraul** [comment]
Just checked your example. I don't need such confusion. I need to prevent from switching at all. I feel that the only way to do it correctly to use external activeItems state. So I need to block your's setState inside handleClick

**Comment by daviferreira** [comment]
OK, what about the `disabled` prop then? :)

**Comment by luckyraul** [comment]
It's easier to maintain one state then recalculate each tab state for disabled .

**Pull request closed without merging**
