### PR TITLE
Allow Accordion active items change

### PR DESCRIPTION
**Pull request by murzvo**
To be able to change accordion ActiveItems dynamically.

### CODE REVIEW

**Comment by murzvo** [comment]
@daviferreira @brukh @psimyn any updates?

**Comment by psimyn** [comment]
Thanks! This is definitely something I want to be able to do, but I'd prefer that we started using activeItems prop directly instead of state.activeItems. `activeItems` is already a bit deceptive due to it being ignored after mounting

I was thinking we add a new component to control state, then Accordion actually takes (and obeys) activeItems prop. Then if you want to handle the activeItems yourself (e.g. in redux state) then you can use Accordion, otherwise you can you StatefulAccordion to retain current behaviour

I had a shot at it in https://github.com/daviferreira/react-sanfona/pull/78/files - I'll have a quick pass at the wrapper component tonight or tomorrow

**Comment by murzvo** [comment]
@psimyn I think that `activeItems` allow is enough functionality for this issue. Also, using the `activeItems` as the component state is not less meaningful as using props value directly

**Comment by psimyn** [comment]
agreed. I'll merge today and make a new release with your changes.

**Comment by murzvo** [comment]
@psimyn good. thank you.

**Comment by murzvo** [comment]
@psimyn what about new release? I really need this changes to stop using my fork in project.

**Comment by eugene-zheng0208** [comment]
@psimyn , @murzvo 
Hey, it would be great if activeItems return actual item objects array, not integers like 0, 1, 2.

**Pull request merged**
