### PR TITLE
Allow override of html tags with props

### PR DESCRIPTION
**Pull request by ghburman**
I wanted to use react-sanfona in a project where I was prohibited from altering the existing markup and this custom-tags feature allowed me to do so. I think it might be useful for others, too.

### CODE REVIEW

**Comment by jimmyspiffy** [comment]
This would be great as I'm needing to put an Icon on the AccordionItems. Currently the <h3> tags are really limiting any customization.

**Comment by daviferreira** [comment]
@ghburman could you rebase against latest master please? Would also be great to add some tests if possible!

Thanks for the contributions!

**Comment by ghburman** [comment]
Rebased against latest master. Added tests.

**Comment by daviferreira** [comment]
Thanks!

**Comment by ghburman** [comment]
You're welcome, @daviferreira.

**Pull request merged**
