### PR TITLE
custom title components. fixes #79

### LINKED ISSUE #79: Make heading configurable in AccodionTitleItem
Would be nice to have the ```<h3>``` configurable in https://github.com/daviferreira/react-sanfona/blob/master/src/AccordionItemTitle/index.jsx#L16. It does not necessary suit the rest of the markup semantic in the application.

Thanks for your nice module! :)

### PR DESCRIPTION
**Pull request by psimyn**
currently ignores onClick that is passed to it though

### CODE REVIEW

**Comment by psimyn** [comment]
@brukh that is fine. The catch is you need to call evt.stopPropagation() in `this.delete` and `this.edit` or the accordionItem will open as well as the action happening.

**Comment by brukh** [comment]
That makes sense. Initially I thought you were trying to override the `handleClick` event with the `onClick` event passed to the title node! Nice work 👍

**Comment by hannupekka** [comment]
Could this be published in NPM also?

**Comment by psimyn** [comment]
I'll publish tonight unless someone beats me to it

**Comment by psimyn** [comment]
@hannupekka published as 0.0.15

**Pull request merged**
