### PR TITLE
Create item disabled option

### PR DESCRIPTION
**Pull request by murzvo**
Disable all actions with `AccordionItem` if it is disabled

### CODE REVIEW

**Comment by brukh** [comment]
Thanks for the PR @murzvo! Can you please add tests for your new feature?

**Comment by murzvo** [comment]
@brukh sure, give me some time

**Comment by murzvo** [comment]
@brukh It's done! Please, check my code again.

**Comment by murzvo** [comment]
@daviferreira @brukh any updates?

**Comment by psimyn** [comment]
Looks fine after a skim, I'll give it bit of a test and merge for you this weekend

**Comment by psimyn** [comment]
1  question: should an open item that gets disabled stay open?

**Comment by murzvo** [comment]
@psimyn I think not. My opinion that if an accordion item is disabled - user cant open it and see the item content.

**Pull request merged**
